spring:
  application:
    name: backend
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 3MB
  ai:
    model:
      chat: ollama
      embedding: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen3:4b
          temperature: 0.2
      embedding:
        model: bge-m3:latest
    vectorstore:
      milvus:
        client:
          host: localhost
          port: 19530
        database-name: default
        collection-name: campus_knowledge
        initialize-schema: true
        embedding-dimension: 1024
        index-type: IVF_FLAT
        metric-type: COSINE
